### PR TITLE
Github actions and style checks

### PR DESCRIPTION
**Pull request by wtrocki**
## Motivation

Detect markdown issues and style issues on PR level by adding github actions capability.
This can be extended later to include extra styling for website etc.

This resolves first part of the #21

### CODE REVIEW

**Comment by wtrocki** [comment]
Actual style changes can be discussed and adjusted (to some extend) etc.

**Review by mhdawson — APPROVED** [review]
LGTM once rebased.

**Comment by wtrocki** [comment]
Rebased. Good to merge

**Comment by wtrocki** [comment]
Build is passing now and all styles were updated. 
Thank you for review

**Comment by mhdawson** [comment]
@wtrocki thank you !

**Pull request merged**
