### PR TITLE
doc: udpate for recent suggestions

### PR DESCRIPTION
**Pull request by mhdawson**
Refs: https://github.com/nodeshift/nodejs-reference-architecture/issues/73

Signed-off-by: Michael Dawson <mdawson@devrus.com>

### CODE REVIEW

**Comment by mhdawson** [comment]
@wtrocki @InfoSec812

**Comment by mhdawson** [comment]
@wtrocki @InfoSec812, a quick look to confirm this addressed your suggestions would be great

**Comment by InfoSec812** [comment]
> @wtrocki @InfoSec812, a quick look to confirm this addressed your suggestions would be great

Didn't I already review and approve this in a different PR? Anyhow, yes. It looks good to me.

**Comment by mhdawson** [comment]
@InfoSec812 thanks.

**Pull request merged**
